# Generated by Django 4.2 on 2023-04-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myLoginDetials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='app_images/')),
                ('app_name', models.CharField(max_length=100)),
                ('app_link', models.CharField(max_length=200)),
                ('app_category', models.CharField(choices=[('Entertainment', 'Entertainment'), ('Eductional', 'Eductional'), ('Lifestyle', 'Lifestyle'), ('food', 'food'), ('common', 'common'), ('productivity', 'productivity')], default=1, max_length=255)),
                ('sub_category', models.CharField(choices=[('social Media', 'social Media'), ('games', 'games'), ('coding', 'coding'), ('kids', 'kids'), ('clothing', 'clothing'), ('fashion', 'fashion'), ('local', 'local'), ('allindia', 'allindia'), ('common', 'common'), ('utility', 'utility'), ('finance', 'finance'), ('music', 'music'), ('travel', 'travel')], default=1, max_length=255)),
                ('points_amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='myscreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshot/')),
            ],
        ),
        migrations.CreateModel(
            name='myUserDetials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
